### ISSUE TITLE
Add ability to detect simple patterns

### ISSUE THREAD

**Issue by martonilles** [onekey-sec/unblob#263]
This could help manual analysis process and could useful hints to the user.

It would be also interesting to easily add some special pattern detection, especially for unknown chunks to help identifying parts.
Some examples;
- entropy detection with customized chunk size for better accuracy
- padding detection (all 0x00/0xff)
- reoccuring pattern detection

We would need some simple way to include simple patterns (like yara rules, magic detection etc.).

In these  cases we need just detection, no extraction is required.

**Comment by qkaiser** [comment]
I experimented a bit with this earlier this month. It's visible at https://github.com/onekey-sec/unblob/tree/padding-auto-id

Have a look when you got time :)

**Comment by qkaiser** [comment]
Rebased the https://github.com/onekey-sec/unblob/tree/padding-auto-id branch, expect some more work soon.

**Comment by qkaiser** [comment]
Implemented by https://github.com/onekey-sec/unblob/pull/697
