### ISSUE TITLE
add extendable chunk "discovery" option

### ISSUE THREAD

**Issue by martonilles** [onekey-sec/unblob#274]
During extraction when an unknown chunk occurs it would be great to show hints & insights on the unknown chunk so the user can easier analyze the un-identify chunks in a blob.

Currently we do entropy calculation, but there are other possible options to provide hints on the unknown chunks, eg:
- identify if the complete chunk is just padding (only 0x00 or 0xff bytes) and flag the unknown chunk as padding
- identify other known (but currently not extracted) patterns

It would be useful if the user could also add other "simple" discovery options that can report hints as well

**Comment by martonilles** [comment]
Similar to #263

**Comment by qkaiser** [comment]
Being worked on in branch https://github.com/onekey-sec/unblob/tree/padding-auto-id
