### ISSUE TITLE
distinguish between _carve and _extract directory

### ISSUE THREAD

**Issue by e3krisztian** [onekey-sec/unblob#326]
just wondering, but do not we want to distinguish between _carve and _extract directory?

_Originally posted by @martonilles in https://github.com/IoT-Inspector/unblob/pull/323#discussion_r841237372_

**Comment by qkaiser** [comment]
This has been implemented with https://github.com/onekey-sec/unblob/pull/1017, leaving it up to the user to configure custom suffix for `_carve` and `_extract` if they want.
