### ISSUE TITLE
Logs from LIEF escape to stderr

### ISSUE THREAD

**Issue by vlaci** [onekey-sec/unblob#391]
While testing #390 I've noticed that sdome logs escape to stderr from [lief](https://github.com/lief-project/LIEF/blob/f8c711dd940ba2c1dbf8cb803e7df2d19bec7853/src/ELF/Parser.tcc#L70). Having a bunch of these lines: `The current binary doesn't have a section header`

It looks like, there is an ability to [control logging from python](https://lief-project.github.io/doc/latest/api/python/index.html#logging), that we need to tinker with.

**Comment by QKaiser** [comment]
I see two ways of doing this:

```python
lief.logging.disable()
```

or 

```python
lief.logging.set_level(lief.logging.LOGGING_LEVEL.CRITICAL)
```
