### ISSUE TITLE
Static site documentation

### ISSUE THREAD

**Issue by kissgyorgy** [onekey-sec/unblob#402]
- [x] Set up Material for MkDocs https://squidfunk.github.io/mkdocs-material/
- [x] Pages:
   - [x] Home/About
   - [x] User Guide @kissgyorgy 
   - [x] Installation
   - [x] Supported Formats
   - [x] Extractors
   - [x] Development guide @kissgyorgy 
   - [x] Glossary @kissgyorgy 
   - [x] Support
- [x] Eye-candy architecture picture, put it under "How does it work?" in About page.
- [x] Demo with asciinema and https://github.com/marionebl/svg-term-cli
- [x] Move wiki pages to documentation @kissgyorgy 
- [x] Branding and theme:
  - [x] set up social cards: https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
  - [x] Company branding style @martonilles 
- [x] Deployment:
  - [x] Self-host asciinema demo, sometimes it's loads very slowly. or try: https://nbedos.github.io/termtosvg/
  - [x] Publish generated pages with GitHub CI to GitHub pages
  - [x] register domain in DNS @martonilles 
  - [x] set DNS records to registered domain [GitHub documentation about domain settings](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site)
- [x] delete most of README and point to documentation
- [x] Fix Source install section, it doesn't work if followed step-by-step: https://github.com/onekey-sec/unblob/issues/418
---
- [x] Pages:
  - [x] API reference
- [x] Set up https://github.com/mkdocstrings/mkdocstrings for API generation
- [ ] Make the public API documented
- [ ] Github issue template instead of "Reporting a Bug" page

**Comment by kissgyorgy** [comment]
`svg-term-cli` generates a huge file, which eats my browsers memory and crashes the page 😄 so I just include the embedded asciinema recording: [![asciicast](https://asciinema.org/a/Q71Vc6IrH0SUNoDA51jxHswKj.svg)](https://asciinema.org/a/Q71Vc6IrH0SUNoDA51jxHswKj)

**Comment by vlaci** [comment]
I used https://nbedos.github.io/termtosvg/ in the past  but it is unmaintained. Do we need debug output anyway?

**Comment by martonilles** [comment]
API reference should go in v2

**Comment by kissgyorgy** [comment]
> Do we need debug output anyway?

I first tried without debug output, but I wanted to keep it real-time, as it takes 15 seconds total, but without debug, nothing happens for a long time. This way, while the reader gets through the log lines, something else with happen, so I found it the best balance between timing, readability and wow effect.

**Comment by kissgyorgy** [comment]
I'm ready with the content. #410
