### ISSUE TITLE
update dependencies & include grype tests in build chain

### ISSUE THREAD

**Issue by flukavsky** [onekey-sec/unblob#409]
Running grype (https://github.com/anchore/grype) against unblob returns the following results:

[grype-vulnerabiltiy-report.txt](https://github.com/onekey-sec/unblob/files/9113368/grype-vulnerabiltiy-report.txt)
 
We should check if we can remove some dependencies that are not required and if there is a newer base-container available. Also, it would make sense to integrate grype into our build chain for periodic tests.

**Comment by qkaiser** [comment]
@flukavsky long time coming but PR has been opened :)
