### ISSUE TITLE
Unblob isnt recognized as argument

### ISSUE THREAD

**Issue by Y8765** [onekey-sec/unblob#418]
After installing the script manually from github and the dependencies and want to run the unblob suite the terminal odsent recognize it at all ,am i missing something?
![image](https://user-images.githubusercontent.com/84688142/184178883-c9c9df66-391a-4434-a393-57ada85dafb4.png)

**Comment by QKaiser** [comment]
Can you try with `poetry run unblob` from the unblob directory ?

From the unblob directory you can also try:

```
poetry shell
unblob
````

**Comment by QKaiser** [comment]
Poetry performs the installation in a dedicated virtual environment, it's not a system wide install. We should probably mention it in the documentation.

**Comment by Y8765** [comment]
> Can you try with `poetry run unblob` from the unblob directory ?
> 
> From the unblob directory you can also try:
> 
> ```
> poetry shell
> unblob
> ````

Thanks for the reply.
Will try tommorow and Will update 👌

**Comment by Y8765** [comment]
> Can you try with `poetry run unblob` from the unblob directory ?
> 
> From the unblob directory you can also try:
> 
> ```
> poetry shell
> unblob
> ```

poetry run working great :)

**Comment by kissgyorgy** [comment]
Thanks for the feedback, we will improve the documentation with this!
