### ISSUE TITLE
Release Docker image to Docker Hub

### ISSUE THREAD

**Issue by kissgyorgy** [onekey-sec/unblob#434]
under onekey-sec/unblob

**Comment by QKaiser** [comment]
Created an account under `onekeyrl` to park it (`onekeysec` and `onekey` are taken, dashes and underscores are not accepted).

What's the added value of pushing to Docker Hub if we push to the Github Docker registry already ?

**Comment by kissgyorgy** [comment]
Some discoverability and the "prettier" name, so someone could simply write "docker run onekey-sec/unblob", because docker.io is hardcoded in the docker binary as default when the registry part is missing, but giving that a second thought, not much of an improvement really.
