### ISSUE TITLE
unblob cannot scan files larger than 4GB

### ISSUE THREAD

**Issue by QKaiser** [onekey-sec/unblob#477]
Due to the following limitation of Hyperscan (see https://github.com/intel/hyperscan/issues/118):

> hs_scan, hs_scan_vector and hs_scan_stream use an unsigned int parameter for providing the length of the buffer to scan. This effectively limits the length to 4GB-1. [0]

Unblob is not able to identify patterns within files larger than 4GB in size. This is problematic for our larger samples.

A naive but somewhat effective approach would be to switch to streaming mode with Hyperscan.

```diff
--- a/unblob/finder.py
+++ b/unblob/finder.py
@@ -146,16 +146,15 @@ def search_chunks(  # noqa: C901
     )
 
+    CHUNK_SIZE = (100 * 1024 * 1024)  # 100MB or whatever arbitrary value
 
     try:
-        hyperscan_db.scan(
-            [
-                file[i : i + CHUNK_SIZE]  # noqa: E203
-                for i in range(0, file.size(), CHUNK_SIZE)
-            ],
-            match_event_handler=_hyperscan_match,
-            context=hyperscan_context,
-        )
+        with hyperscan_db.stream(match_event_handler=_hyperscan_match, context=hyperscan_context) as stream:
+            for i in range(0, file.size(), CHUNK_SIZE):
+                logger.info("scanning range", start=i, end=i+CHUNK_SIZE)
+                stream.scan(
+                    file[i : i + CHUNK_SIZE], # noqa: E203
+                )
     except hyperscan.error as e:
         if e.args and e.args[0] == f"error code {hyperscan.HS_SCAN_TERMINATED}":
             logger.debug(
@@ -178,7 +177,9 @@ def search_chunks(  # noqa: C901
 
 @lru_cache
 def build_hyperscan_database(handlers: Handlers) -> Tuple[hyperscan.Database, Dict]:
-    db = hyperscan.Database(mode=hyperscan.HS_MODE_VECTORED)
+    db = hyperscan.Database(
+        mode=(hyperscan.HS_MODE_STREAM | hyperscan.HS_MODE_SOM_HORIZON_LARGE)
+    )
     handler_map = dict()
```

This would require a bit of work to adapt our test suite and making sure we keep track of the current chunk start offset in the scanning context, but it's entirely doable.

By scanning chunks of the file in streaming mode, we could skip entire chunks of data in they are within an already identified chunks. I'm sure this would bring a massive speed up for the first outer layers. Instead of waiting for all the matches to call back, we would simply skip over them. Memory usage should also be lowered if we choose our chunk sizes wisely.

Doing this would lift the size limits imposed by Hyperscan in block or vector mode.

**Comment by vlaci** [comment]
It is a tiny bit more complicated than the diff indicates, slicing into the mmap value would force the data to be loaded into memory.

**Comment by QKaiser** [comment]
So I did some alloc tracing with `mprof`, it would be ideal to move to streaming mode in smaller chunks and deallocate scanned chunks when we're done with them.

Otherwise, the whole file gets allocated through mmap thanks to Hyperscan in vectored mode:

![image](https://user-images.githubusercontent.com/569494/205684088-8235dc7b-9196-48d5-8ccb-b5456bb5c404.png)

**Comment by QKaiser** [comment]
> It is a tiny bit more complicated than the diff indicates, slicing into the mmap value would force the data to be loaded into memory.

After a bit of investigation, the trick here would be to call  `madvise()` on each loop to tell the underlying system that the chunk we just scanned can be released.

I would go for a non-Linux specific advice such as MADV_DONTNEED:

```
MADV_DONTNEED

Do not expect access in the near future.  (For the time being, the application is finished with the given range,
so the kernel can free resources associated with it.)

After  a successful MADV_DONTNEED operation, the semantics of memory access in the specified region
are changed: subsequent accesses of pages in the range will succeed, but will result in either repopulating
the memory contents from the up-to-date contents of the underlying mapped file (for shared file mappings,
shared anonymous mappings, and shmem-based techniques such as  System V shared memory segments)
or zero-fill-on-demand pages for anonymous private mappings.

Note  that,  when  applied to shared mappings, MADV_DONTNEED might not lead to immediate freeing
of the pages in the range.  The kernel is free to delay freeing the pages until an appropriate moment. 
The resident set size (RSS) of the calling process will be immediately reduced however.

MADV_DONTNEED cannot be applied to locked pages, Huge TLB pages, or VM_PFNMAP pages.
(Pages marked with the kernel-internal VM_PFNMAP flag are special memory areas that are  not 
managed  by the virtual memory subsystem.  Such pages are typically created by device drivers
that map the pages into user space.)
```

Something like:

```python
with hyperscan_db.stream(match_event_handler=_hyperscan_match, context=hyperscan_context) as stream:
    for i in range(0, file.size(), PAGE_SIZE):
        logger.info("scanning range", start=i, end=i+PAGE_SIZE)
        stream.scan(
            file[i : i + PAGE_SIZE], # noqa: E203
        )
        file.madvise(mmap.MADV_DONTNEED, i, PAGE_SIZE)
```

I see a few things we need to keep in mind though:
- the fact that handlers could read past the current chunk provided to Hyperscan streaming scanner is not a problem in itself, but could defeat our attempt to release memory with madvise. Imagine a compression stream handlers searching for the end of the stream and reading 1GB of data. A valid chunk is found and we resume the scan right after that valid chunk, At that point, we should be aware that we need to madvise the whole chunk that just got found.
- this could pose a problem when carving chunks once all the chunks have been identified within a file. Since we're relying on Python's mmap.mmap defaults in unblob the mapping is SHARED, which means it would be repopulated transparently at that point. So we're good, but it would be advised (pun intended) to use `madvise` in functions like `carve_chunk_to_file` to limit the resident set size of unblob when carving too.

Combining these two points, finding -> carving -> madvising would be a good strategy imho.
