### ISSUE TITLE
Can't use unblob command line interface after installing on ubuntu 22.10

### ISSUE THREAD

**Issue by TissuePowder** [onekey-sec/unblob#489]
I followed the steps mentioned here https://unblob.org/installation/
I am on ubuntu 22.10. Installed from source. I have installed the mentioned dependencies.

```
$ poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: unblob (0.1.0)
```
```
$ unblob
zsh: command not found: unblob
```
I tried install both with and without sudo, same issue. What could be the problem or what am I missing?

**Comment by QKaiser** [comment]
Hi there ! Poetry installs unblob in a self-contained virtualenv so if you want to execute it you need to do it this way:

```
poetry run unblob
```

Alternatively, you can build an unblob package and install it system wide:

```
poetry build
sudo python3 -m pip install dist/unblob-0.1.0.tar.gz
```

**Comment by TissuePowder** [comment]
Ah, thank you for clearing it up. Mention this in the documentation too please, in case someone else finds themselves the same problem.

After I install it system-wide, do I need to run any additional command if I want to remove it from poetry's self-contained venv? And can I safely delete the git directory I initially cloned?
