### ISSUE TITLE
PyPI release error

### ISSUE THREAD

**Issue by kissgyorgy** [onekey-sec/unblob#501]
This is a tough one: https://github.com/onekey-sec/unblob/actions/runs/4044691266/jobs/6955168536
Sorry I did not know about PEP 440: https://peps.python.org/pep-0440/#direct-references.
direct references on external links won't be allowed for good reasons: https://github.com/pypa/pip/issues/6301

This means we can only have dependencies, which has releases themselves on PyPI, but we can't because `ubi-reader` is our fork and the original is already released: https://pypi.org/project/ubi-reader/

There are multiple solutions:
1. ~~Vendor everything.~~ We would subtree merge these projects next to unblob, install them from the same directory, but still handle them as separate packages, no Python code change would be necessary, just build and release.
We can't do this, as ubi-reader is GPLv3...: https://github.com/jrspruitt/ubi_reader/blob/master/LICENSE
3. Talk to `yaffshiv` and `ubi-reader` authors, release `jefferson` ourself. This would be probably the cleanest, but most work, because we need to coordinate with them not just the release, but integrating our changes too. This is good open source citizenship and in an ideal work, we should do this one 😄
4. Make a separate package something like `unblob-extractors` and vendor them there. Maybe unblob would not even be a dependency of that package just an extra, so installation could be done like this `pip install unblob[extractors]`.

**Comment by QKaiser** [comment]
I'm in favor of option 3.

While we have control of `jefferson` and the maintainer of `ubi-reader` is super cool (fast integration of our fixes, version bump, and publication to PyPi), `yaffshiv` seems to be a dead project right now. Yaffshiv maintainers did not react to the [PR with security implications](https://github.com/devttys0/yaffshiv/pull/3) for the last 90 days, which makes me think they probably won't answer our call for proper versioning and publication to PyPi.

I would create an `unblob-extractors` repo with git submodules pointing to our different forks.

**Comment by kissgyorgy** [comment]
Than 2. would be simpler, because we can fork `yaffshiv` to a different name (MIT licensed so no problem) and release it ourself. We can release `jefferson` as it is as you own it, and only `ubi-reader` is left, which we can coordinate with the original developer.

**Comment by QKaiser** [comment]
I'm okay with that ! We can make unblob rely on ubi-reader at https://pypi.org/project/ubi-reader/ rather than our fork (we just keep our fork for the occasional fix + PR flow).

I'll make some time to adapt jefferson so that we use Poetry there too.

Any naming ideas for our `yaffshiv` fork other than `yaffshiv-ng` ? 😛 

Note about `yaffshiv`: I'm seriously considering porting the YAFFS extraction logic  to an unblob extractor. This would be one less package to care about.

**Comment by kissgyorgy** [comment]
> We can make unblob rely on ubi-reader at https://pypi.org/project/ubi-reader/

Is it in sync with the fork?

> Any naming ideas for our `yaffshiv` fork other than `yaffshiv-ng`

We don't have to be creative, `yaff-extractor` or something dull would do it 😄 

> Note about `yaffshiv`: I'm seriously considering porting the YAFFS extraction logic to an unblob extractor. This would be one less package to care about.

That's a great idea. I wanted to suggest to just strip the extraction logic, so there would be less code to maintain.

**Comment by QKaiser** [comment]
> Is it in sync with the fork?

Not exactly. We're behind for the latest developments made by the maintainer and we have a few improvements yet to submit (fix a dependency name, remove superfluous extraction directory). I'll look into it.

**Comment by QKaiser** [comment]
Let's keep track of things that needs to be done:

- [ ] sync with ubi-reader, move from our fork to ubi-reader on PyPi
- [ ] adapt Jefferson, sync with original maintainer, publish to PyPi, move from our fork to jefferson on PyPi
- [ ] port YAFFS extraction to unblob

**Comment by qkaiser** [comment]
We're now on PyPi. Good job everyone :)
