### ISSUE TITLE
Seemingly no working install options for mac

### ISSUE THREAD

**Issue by Qwertie-** [onekey-sec/unblob#502]
Had a go at the pip, docker, and from source and none work 

pip:

```
python3 -m pip install --user unblob
ERROR: Could not find a version that satisfies the requirement unblob (from versions: none)
ERROR: No matching distribution found for unblob

```

Docker:
```docker: no matching manifest for linux/arm64/v8 in the manifest list entries.```

From source:

Fails to install python-lzo `ld: library not found for -llzo2`
lzo has been installed via homebrew.

Have not tried the nix option yet. Wondering if anyone has got this running on an Apple Silicon mac yet and what method they went with.

**Comment by QKaiser** [comment]
Unblob has yet to be released on PyPi so it can't be installed with pip, this is our main focus right now (see https://github.com/onekey-sec/unblob/issues/501).

We have an open ticket to release Docker images for ARM and ARM64 at https://github.com/onekey-sec/unblob/issues/417, which is also linked to https://github.com/onekey-sec/unblob/issues/479.

Some initial research into installing unblob on Mac with Nix: https://github.com/onekey-sec/unblob/issues/494

I would recommend keeping an eye on those issues to monitor progress and help out.

Closing as dup of #501 , #417, #479, #494
