### ISSUE TITLE
Rust binding is missing from the wheel on Pypi

### ISSUE THREAD

**Issue by vlaci** [onekey-sec/unblob#562]
The release build differs from how we build it for the docker image:

https://github.com/onekey-sec/unblob/blob/c5837b770b6dd7705fb0c517234462c14068d77e/.github/workflows/build-publish-image.yml#L28

https://github.com/onekey-sec/unblob/blob/c5837b770b6dd7705fb0c517234462c14068d77e/.github/workflows/release.yml#L18

I'd adwise to build wheels for all main branch merges and store them as artifacts. Tests should also run against the wheel built that way.  The release should just fetch the artifact matching the tag and publish it. That way we ensure that the wheel is tested and works properly.

Also, the wheel contains the rust source code.

**Comment by qkaiser** [comment]
Duplicate of https://github.com/onekey-sec/unblob/issues/561 ?

**Comment by vlaci** [comment]
Github is acting up, sorry
