### ISSUE TITLE
Rename directory so all users may clone repo

### ISSUE THREAD

**Issue by pm64** [onekey-sec/unblob#596]
Currently, a particular directory in this repo is preventing some users from being able to clone it.

Specifically, the directory `tests/integration/archive/dmg/__output__/fruits_osx.compressed.dmg_extract/fruits/.HFS+ Private Directory Data?/` contains a question mark in the filename, which isn't supported on Windows-based filesystems.

Please consider renaming this directory.

**Comment by qkaiser** [comment]
Hi @pm64 !

We do not provide support for Windows platforms, only Linux and MacOS systems.

Are you planning on contributing ? Otherwise I recommend you install unblob through `pip`, `nix`, or run it in Docker (see https://unblob.org/installation/). It will be easier.
