### ISSUE TITLE
add option to only "scan" the binary like binwalk would do for example

### ISSUE THREAD

**Issue by dummys** [onekey-sec/unblob#624]
Hi,

I would like to skip using binwalk and use your tools rather, but I'm missing one of the binwalk feature, ability to simply scan the whole binary and print all know files inside.
I checked the command line of unblob and found one that should do the same, the "-s" option, but I get directory of extraction still created. Is is possible to avoid creating and thus clobbering the working directory with "*_extract" folder ?

**Comment by qkaiser** [comment]
Hi @dummys ! That's something we talked about in the early days of unblob development but never got to implement.

I'll keep the issue open to track it, but please note that it's not on our priority list.

**Comment by aserper** [comment]
+1

**Comment by qkaiser** [comment]
@dummys @aserper please have a look at #692 and do not hesitate to comment. I'd like to know what are your expectations regarding the console output in "scan" mode.

> Is is possible to avoid creating and thus clobbering the working directory with "*_extract" folder ?

This is handled by 6aabbc7c692078b9e7c5b2a64b4df239b500a1c2 right now. This will probably land in main in 2024.
