### ISSUE TITLE
Infinite loop in zstd handler calculate_chunk()

### ISSUE THREAD

**Issue by gluesmith2021** [onekey-sec/unblob#634]
# Description

Given an invalid or truncated zstd file, `unblob/handlers/compression/zstd.py`, in `calculate_chunk()`, does not check for EOF in the `while` loop. 

After reaching EOF, it always "reads" a block of type 0 and of size 0. This is a valid block type (i.e. no raised exception) but not an "end block" type, which is the only other condition to exit the loop. Therefore, it keeps looping actively and never returns. 

Note: `read()` operation is from a `mmap.mmap` and the latter does not raise an exception when reading past the EOF. It rather "silently adjusts" the requested read size to match remaining size, here 0.  

# To Reproduce

This 9-byte file triggers the bug:

```shell
echo -n -e "\x28\xb5\x2f\xfd\x00\x00\x04\x00\x00" > unblob_dos 
unblob unblob_dos 
```

Example is with the CLI for the sake of simplicity, but the same problem occurs through Python API. 

# Expected Behavior

`unblob` finishes chunk calculation (probably by raising some exception to discard the chunk)

# Environment

Probably not that relevant here, but just in case:
- Ubuntu under WSL 
  - Ubuntu 22.04.2 LTS
  - 5.15.90.1-microsoft-standard-WSL2
- Python 3.10.6 with Poetry 1.5.1

**Comment by qkaiser** [comment]
Thank you for your detailed report. I reproduced the bug and tagged the issue. Will keep you posted.
