### ISSUE TITLE
Add python 3.12 to our test matrix

### ISSUE THREAD

**Issue by qkaiser** [onekey-sec/unblob#666]
Our [current test matrix](https://github.com/onekey-sec/unblob/blob/main/.github/workflows/run-tests.yml#L55) run tests on Python 3.8, 3.9, 3.10, and 3.11.

With the recent introduction of Python 3.12 we're seeing an uptick in unblob downloads coming from that version:

![image](https://github.com/onekey-sec/unblob/assets/569494/a89b856a-ea69-4853-b0e3-7450832afed9)

Time to extend the tests :)

**Comment by vlaci** [comment]
All those arch users :)
