### ISSUE TITLE
Support aarch64-darwin "Apple Silicon" devices

### ISSUE THREAD

**Issue by ljrk0** [onekey-sec/unblob#724]
**Is your feature request related to a problem? Please describe.**
#516 added macOS x86 and Linux ARM support but macOS ARM isn't supported:

```
error: flake 'github:onekey-sec/unblob' does not provide attribute 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
```

**Describe the solution you'd like**
Support for the aarch64-darwin target in the build pipeline.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by qkaiser** [comment]
Hi @ljrk0 ! I'm only seeing your issue now, it the darwin-aarch64 package should be available now. We're building it using Github Apple M1 runner since https://github.com/onekey-sec/unblob/pull/741

Can you confirm it works ?

**Comment by ljrk0** [comment]
Thank you for coming back to me!  I missed though that the core issue is not the CI but the build flake for Nix not claiming macOS on ARM support.  Had some time to investigate and add the small fix :)
