### ISSUE TITLE
Error trying to extract ubi files.

### ISSUE THREAD

**Issue by markyy1991** [onekey-sec/unblob#750]
Hello everyone, I am trying to extract the contents of 2 ubi files, and I am getting an error with the software presented here.

Any idea how to fix it and extract the content from these?

It should be noted that these files have the OOB removed. But it still doesn't work.

I leave the link to the files here in case someone can shed some light.

Thanks to all :)

https://fromsmash.com/ubi-files

**Comment by qkaiser** [comment]
Did you close it by accident ? :) You can attach the file here and we'll investigate.

**Comment by markyy1991** [comment]
No, its here:

https://github.com/onekey-sec/ubi_reader/issues/91

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
