### ISSUE TITLE
Safe Tarfile incorrectly blocks Symlink Traversal Attempt

### ISSUE THREAD

**Issue by AndrewFasano** [onekey-sec/unblob#769]
(I'm attempting to break #763 and #761 into smaller issues with concrete bugs and examples)

Filesystem: https://files.dlink.com.au/Products/DCS-6517/REV_B/Firmware/Firmware_2.00.03/DCS-6517B1_FW_v2.00.03.zip

Binwalk extraction produces 173 symlinks that unblob drops. For example `sbin/init -> ../bin/busybox`. Unblob does not produce these due to incorrect symlink handling in `_safe_tarfile.py`

```
2024-02-14 18:19.09 [warning  ] Traversal attempt through link path. Skipped. path=sbin/init pid=58
```

Tested with head of main and #768, both produce the same behavior (since this bug is specific to the logic in safe_tarfile)

**Comment by e3krisztian** [comment]
With #775 merged, all but one symlinks are extracted:

```sh
DCS-6517B1_FW_v2.00.03.zip_extract/DCS-6517B1_FW_v2.00.03.pkg_extract/44-17853067.gzip_extract/gzip.uncompressed_extract$ find -type l -ls | wc -l
347
```
