### ISSUE TITLE
CI: automated weekly releases

### ISSUE THREAD

**Issue by qkaiser** [onekey-sec/unblob#774]
I would like to have weekly releases of unblob fully automated through Github CI.

The auto version update workflow would:
- pull the code
- set the calendar version in `pyproject.yml`
- commit the change
- tag the commit with version
- push the branch
- open a pull request

When that automated PR gets approved by a maintainer, auto-release workflow would pick it up and create a release:

https://github.com/marketplace/actions/auto-release

This would then trigger our release workflow with publication to PyPi.

**Comment by martonilles** [comment]
do we need weekly release? Isn't it too frequent?

**Comment by qkaiser** [comment]
> do we need weekly release? Isn't it too frequent?

can be bi-weekly or monthly, just want it to be automated like our dependencies update :)

**Comment by qkaiser** [comment]
Given how we operate this repo, I no longer think this is relevant. Closing.
