### ISSUE TITLE
zlib file carving

### ISSUE THREAD

**Issue by jstucke** [onekey-sec/unblob#939]
zlib files are supported by unblob _but_ only as whole files and not inside other files (e.g. binary blobs) because of how the regexes in the pattern are written. Was this a deliberate decision for performance reasons? 

I have a PE file containing a firmware update (which I sadly cannot share) with included zlib streams and unblob is unable to extract them as it currently is (unlike binwalk). I tried changing the patterns in the `ZlibHandler` so that they do not need to start at the beginning of the file and this is enough to successfully extract everything from the file.

If performance considerations were the idea behind this, could adding this as an CLI parameter be an option?

unblob log without zlib carving:

<details>

```
unblob -v update.exe
2024-09-03 14:00.36 [debug    ] Logging configured             extract_root=. pid=602569 vebosity_level=1
2024-09-03 14:00.36 [info     ] Start processing file          file=update.exe pid=602569
2024-09-03 14:00.36 [debug    ] Processing file                path=update.exe pid=602572 size=0x1a7434
2024-09-03 14:00.36 [debug    ] Ended searching for chunks     all_chunks=[] pid=602572
2024-09-03 14:00.36 [debug    ] Calculating entropy for file   path=update.exe pid=602572 size=0x1a7434
2024-09-03 14:00.36 [debug    ] Entropy calculated             block_size=0x54a7 highest=99.89 lowest=18.75 mean=96.01 path=update.exe pid=602572 size=0x1a7434
```

</details>

unblob log with zlib carving:

<details>

```
╭─────────────────── unblob (24.6.10) ────────────────────╮
│ Extracted files: 81                                     │
│ Extracted directories: 11                               │
│ Extracted links: 0                                      │
│ Extraction directory size: 3.48 MB                      │
│ Chunks identification ratio: 54.56%                     │
╰───────────────────────── Summary ───────────────────────╯
        Chunks distribution        
┏━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Chunk type ┃   Size    ┃ Ratio  ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ ZLIB       │  1.49 MB  │ 49.91% │
│ UNKNOWN    │  1.36 MB  │ 45.44% │
│ ZIP        │ 142.05 KB │ 4.65%  │
└────────────┴───────────┴────────┘
```

</details>

patch: 
[zlib_patch.txt](https://github.com/user-attachments/files/16850133/zlib_patch.txt)

**Comment by martonilles** [comment]
This is a very difficult topic and yes it was a deliberate decision to implement it like this, it was actually just changed recently in #829. The main reason was actually performance and accuracy not to pick up too much garbage.

We have seen cases where it caused missing chunks, but in most cases it just picked up some compressed parts not properly handled by other handlers. Never the less there could be still valid cases, where the zlib starts somewhere in the file, rather at the beginning.

I generally see a few options to move forward, if we want to handle this:
- implement a variation of the current handler that could pick up zlib chunks anywhere in the file, while keeping the current zlib at start handler, This way we can default to the current one, but somehow make it configurable to use the other when needed
- improve the pattern/handler to produce less matches, though unfortunately I am not sure how this could be done, we tried and could not come up with better solution. If you have any suggestion, idea we would be super happy ;)

Alternatively you can implement a variation of the handler, just by overriding the patterns and create a local copy for your environment. unblob can dynamically load your plugin which could have this handler. This way you can have your local handlers and do not need to modify unblob.

**Comment by jstucke** [comment]
Thank you for the detailed answer. I also feared that this would cause a lot of false positives, but I was positively surprised that all of them were apparently filtered out in my case during the extraction (apparently causing `zlib.error`s and there were over a hundred possible wrong start bytes in the outermost file alone). So the risk of false positives does not seem to be that high (maybe thanks to the checksum at the end).  I share your concerns regarding performance, though: I tested it with a 64 MB random file and with "zlib carving" unblob took roughly  30% longer (which is arguably a lot just for this single format).

**Comment by jstucke** [comment]
> improve the pattern/handler to produce less matches, though unfortunately I am not sure how this could be done, we tried and could not come up with better solution

I'm not sure if this would even be possible because of how minimalist the zlib header is (it does not come with a magic string, you only get those two bytes that are already in the pattern)

I did not find any docs regarding the plugin feature but after some tinkering I was able to write a simple plugin which provides the functionality:

```python3
from unblob.handlers.compression.zlib import ZlibHandler
from unblob.models import HexString
from unblob.plugins import hookimpl


@hookimpl
def unblob_register_handlers():
    yield from [ZlibCarvingHandler]


class ZlibCarvingHandler(ZlibHandler):
    NAME = "zlib_carver"

    PATTERNS = [
        HexString("78 01"),  # low compression
        HexString("78 9c"),  # default compression
        HexString("78 da"),  # best compression
        HexString("78 5e"),  # compressed
    ]
```

Do you think it would make sense to have a dedicated CLI option for this (or maybe for slower unpackers in general)? If so, I could create a PR.
