### ISSUE TITLE
Dropping support for Python 3.8 at the end of the year

### ISSUE THREAD

**Issue by vlaci** [onekey-sec/unblob#998]
Python 3.8 reached EOL on 2024-10-07. Our dependencies will likely drop support for that version as well, so it will be a burden to keep-up support for it sooner or later.

The plan is to release a final version supporting Python 3.8 at around December-January.

Should you have any questions or comments about the timeline, please comment on this issue.

**Comment by qkaiser** [comment]
A good first step would be to move away from `python:3.8-slim` in our [Dockerfile](https://github.com/onekey-sec/unblob/blob/main/Dockerfile) ...
